   - name: å¼€å§‹ðŸ”„è‡ªåŠ¨åŒæ­¥ðŸ”„
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/wuzhi04/MyActions.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
      # æˆ‘è‡ªå·±åŒæ­¥åˆ°giteeä½¿ç”¨ï¼Œå…¶ä»–äººå¯å¿½ç•¥
      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.dst_key
        with:
          src: github/wuzhi03
          dst: gitee/shuye72
          static_list: "MyActions"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
